name: Pomopilot
options:
  bundleIdPrefix: com.rinngroup
  deploymentTarget:
    iOS: 16.0
targets:
  Pomopilot:
    type: application
    platform: iOS
    sources:
      - PomopilotApp.swift
      - ContentView.swift
      - DebugHelper.swift
      - Managers
      - Models
      - Views
      - Assets.xcassets
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSUserActivityTypes:
          - com.rinngroup.pomopilot.session
        NSMicrophoneUsageDescription: "Pomopilot needs microphone access to enable voice interaction with the AI assistant."
        NSSpeechRecognitionUsageDescription: "Pomopilot needs speech recognition permission to understand your voice commands."
        # Gemini API key
        GEMINI_API_KEY: "AIzaSyBqP70sf6WHU61M3lDm5Qs2zgTcshuf4o8"
    settings:
      base:
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        DEVELOPMENT_TEAM: "" # You can add your team ID here if needed
    dependencies:
      - package: GoogleGenerativeAI
packages:
  GoogleGenerativeAI:
    url: https://github.com/google/generative-ai-swift
    from: 0.5.0 # Using latest version that supports Live API 